name: running_movil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  animate_do: ^4.2.0
  flutter_map: ^8.2.1
  firebase_storage: ^13.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  notification_listener_service: ^0.3.4
  timezone: ^0.10.1
  awesome_notifications: ^0.10.1
  latlong2: ^0.9.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/running_logo.png"
  adaptive_icon_background: "assets/images/running_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/running_logo.png
    - assets/images/ruta.png
    - assets/images/reloj1.png
