// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD-I3DwFq7kItySZnkAJMSBhKjK8hqXVg',
    appId: '1:1038604616337:web:2c7000e2239f0f2df87530',
    messagingSenderId: '1038604616337',
    projectId: 'running-3e33f',
    authDomain: 'running-3e33f.firebaseapp.com',
    storageBucket: 'running-3e33f.firebasestorage.app',
    measurementId: 'G-WYYM4J4435',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdE3s2n4ckmmThzM-fu6RD7chsJM5Kbw',
    appId: '1:1038604616337:android:44b7268df80a4329f87530',
    messagingSenderId: '1038604616337',
    projectId: 'running-3e33f',
    storageBucket: 'running-3e33f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD-I3DwFq7kItySZnkAJMSBhKjK8hqXVg',
    appId: '1:1038604616337:web:03b212938b52a309f87530',
    messagingSenderId: '1038604616337',
    projectId: 'running-3e33f',
    authDomain: 'running-3e33f.firebaseapp.com',
    storageBucket: 'running-3e33f.firebasestorage.app',
    measurementId: 'G-TZPDCNMJRK',
  );
}
